"""add sequence column to messages

Revision ID: ff8b8970fcc6
Revises: 871b429cb50d
Create Date: 2026-04-23 12:05:11.456346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff8b8970fcc6'
down_revision: Union[str, None] = '871b429cb50d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'sequence',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_messages_sequence'), 'messages', ['sequence'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_sequence'), table_name='messages')
    op.alter_column('messages', 'sequence',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
